name: BUILD

on:
  push:
    branches: [ master ]

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all

  ubuntu20_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make all
