name: Windows

on:
  push:
    branches: [ master ]

env:
  SOLUTION_FILE_PATH: .

jobs:
  
  win2019_build:
    strategy:
      matrix:
        platform: [x86,x64]
        method: [Debug,Release]
      
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir -p build
        cd build
        cmake .. -A ${{ matrix.platform }}
        cmake --build . --config ${{ matrix.method }}
        .\test\${{ matrix.method }}\test.exe
