name: Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  ubuntu18_04_build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j `nproc`
        ./test/test

  ubuntu20_04_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        mkdir -p build
        cd build
        cmake ..
        make -j `nproc`
        ./test/test
