name: windows_package

on:
  workflow_dispatch:
  
  create:
    tags:
      - v*

env:
  BUILD_TYPE: Release

jobs:

  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir -p build_x64
        cd build_x64
        cmake .. -A x64
        cmake --build . --config Release
        .\test\Release\naptest.exe
        run: echo ${{ github.sha }} > Release.txt
        
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: ${{ secrets.TOKEN }}
        files: Release.txt


        
        
      

